# Generated by Django 3.2.16 on 2023-01-17 18:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bouquet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
                ('photo', models.ImageField(upload_to='', verbose_name='фото')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена')),
                ('height_cm', models.PositiveSmallIntegerField(help_text='задается в сантиметрах', validators=[django.core.validators.MinValueValidator(0)], verbose_name='высота')),
                ('width_cm', models.PositiveSmallIntegerField(help_text='задается в сантиметрах', validators=[django.core.validators.MinValueValidator(0)], verbose_name='ширина')),
            ],
            options={
                'verbose_name': 'букет',
                'verbose_name_plural': 'букеты',
            },
        ),
        migrations.CreateModel(
            name='BouquetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название')),
            ],
            options={
                'verbose_name': 'элемент букета',
                'verbose_name_plural': 'элементы букетов',
            },
        ),
        migrations.CreateModel(
            name='DeliveryWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название')),
                ('from_hour', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)], verbose_name='доставить с')),
                ('to_hour', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)], verbose_name='доставить до')),
            ],
            options={
                'verbose_name': 'окно доставки',
                'verbose_name_plural': 'окна доставки',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название')),
            ],
            options={
                'verbose_name': 'событие для букета',
                'verbose_name_plural': 'события для букета',
            },
        ),
        migrations.CreateModel(
            name='FlowerShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, verbose_name='адрес')),
            ],
            options={
                'verbose_name': 'магазин цветов',
                'verbose_name_plural': 'магазины цветов',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена')),
                ('client_name', models.CharField(max_length=200, verbose_name='имя клиента')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU', verbose_name='контактный номер')),
                ('delivery_address', models.CharField(max_length=200, verbose_name='адрес доставки')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email адрес')),
                ('paid', models.BooleanField(verbose_name='оплачен')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата и время создания заказа')),
                ('composed_at', models.DateTimeField(blank=True, null=True, verbose_name='дата и время сбора букета флористом')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='дата и время доставки букета')),
                ('status', models.CharField(choices=[('создан', 'Created'), ('собран', 'Composed'), ('доставлен', 'Delivered'), ('отменен', 'Cancelled')], default='создан', max_length=15, verbose_name='статус заказа')),
                ('bouquet', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='flowerapp.bouquet')),
                ('delivery_window', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='flowerapp.deliverywindow')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
        migrations.CreateModel(
            name='BouquetItemsInBouquet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='количество')),
                ('bouquet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='flowerapp.bouquet')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bouquet_relations', to='flowerapp.bouquetitem')),
            ],
            options={
                'verbose_name': 'элемент букета в букете',
                'verbose_name_plural': 'элементы букета в букете',
            },
        ),
        migrations.AddField(
            model_name='bouquetitem',
            name='bouquets',
            field=models.ManyToManyField(through='flowerapp.BouquetItemsInBouquet', to='flowerapp.Bouquet'),
        ),
        migrations.AddField(
            model_name='bouquet',
            name='events',
            field=models.ManyToManyField(to='flowerapp.Event'),
        ),
    ]
