# Generated by Django 3.2.16 on 2023-01-17 21:24

from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('flowerapp', '0002_auto_20230118_0017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200, verbose_name='имя клиента')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU', verbose_name='контактный номер')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата и время заказа консультации')),
                ('consulted_at', models.DateTimeField(blank=True, null=True, verbose_name='дата и время оказания консультации')),
                ('status', models.CharField(choices=[('создана', 'Created'), ('оказана', 'Consulted'), ('отменена (не доступен)', 'Cancelled')], default='создана', max_length=30, verbose_name='статус консультации')),
            ],
            options={
                'verbose_name': 'консультация',
                'verbose_name_plural': 'консультации',
            },
        ),
    ]
