# Generated by Django 3.2.16 on 2023-01-20 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowerapp', '0005_auto_20230119_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowerShopCatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.BooleanField(db_index=True, default=True, verbose_name='в наличии')),
                ('bouquet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_items', to='flowerapp.bouquet', verbose_name='букет')),
                ('flower_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_items', to='flowerapp.flowershop', verbose_name='магазин цветов')),
            ],
            options={
                'verbose_name': 'пункт каталога магазина цветов',
                'verbose_name_plural': 'пункты каталога магазина цветов',
                'unique_together': {('flower_shop', 'bouquet')},
            },
        ),
    ]
