# Generated by Django 3.2.16 on 2023-01-19 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowerapp', '0005_auto_20230119_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='budget',
            field=models.CharField(blank=True, max_length=100, verbose_name='бюджет'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='event',
            field=models.CharField(blank=True, max_length=100, verbose_name='повод'),
        ),
    ]
