# Generated by Django 3.2.16 on 2023-01-21 14:45

from django.db import migrations, models
import django.db.models.expressions
import django.db.models.functions.datetime


class Migration(migrations.Migration):

    dependencies = [
        ('flowerapp', '0006_auto_20230119_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bouquet',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='bouquetitem',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('создана', 'Created'), ('оказана', 'Consulted'), ('отменена (не доступен)', 'Cancelled')], db_index=True, default='создана', max_length=30, verbose_name='статус консультации'),
        ),
        migrations.AlterField(
            model_name='deliverywindow',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='flowershop',
            name='address',
            field=models.CharField(max_length=200, unique=True, verbose_name='адрес'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('создан', 'Created'), ('собран', 'Composed'), ('доставлен', 'Delivered'), ('отменен', 'Cancelled')], db_index=True, default='создан', max_length=15, verbose_name='статус заказа'),
        ),
        migrations.AlterUniqueTogether(
            name='bouquetitemsinbouquet',
            unique_together={('bouquet', 'item')},
        ),
        migrations.AlterUniqueTogether(
            name='deliverywindow',
            unique_together={('from_hour', 'to_hour')},
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(django.db.models.functions.datetime.TruncDate('created_at'), django.db.models.expressions.F('created_at'), name='cons_created_at_date_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(django.db.models.functions.datetime.TruncDate('created_at'), django.db.models.expressions.F('created_at'), name='order_created_at_date_idx'),
        ),
    ]
