# Generated by Django 3.2.16 on 2023-01-21 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowerapp', '0007_auto_20230121_1745'),
        ('flowerapp', '0007_order_comment'),
    ]

    operations = [
    ]
