# Generated by Django 3.2.16 on 2023-01-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowerapp', '0008_merge_0007_auto_20230121_1745_0007_order_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('создан', 'Created'), ('собирается', 'Composing'), ('собран', 'Composed'), ('доставляется', 'Delivering'), ('доставлен', 'Delivered'), ('отменен', 'Cancelled')], db_index=True, default='создан', max_length=15, verbose_name='статус заказа'),
        ),
    ]
