# Generated by Django 3.2.16 on 2023-01-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('флорист', 'Florist'), ('курьер', 'Courier')], max_length=10, null=True, verbose_name='роль'),
        ),
    ]
